apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-rotator-app
  namespace: config-rotator
  labels:
    app: config-rotator
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: config-rotator
  template:
    metadata:
      labels:
        app: config-rotator
      annotations:
        checksum/config: "init"
    spec:
      containers:
      - name: app
        image: pc4-config-secret-rotator:v1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret
