apiVersion: v1
kind: Service
metadata:
  name: config-rotator-service
  namespace: config-rotator
spec:
  type: ClusterIP
  selector:
    app: config-rotator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
